"""create_trading_signals_and_futures_tables

Revision ID: a9df3ffaea91
Revises: 
Create Date: 2024-12-20 08:26:00.727689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9df3ffaea91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('market_cycle_phase', sa.String(), nullable=True),
    sa.Column('market_volatility', sa.Float(), nullable=True),
    sa.Column('market_volume', sa.Float(), nullable=True),
    sa.Column('market_sentiment', sa.String(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('technical_indicators', sa.JSON(), nullable=True),
    sa.Column('sentiment_sources', sa.JSON(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('margin_type', sa.Enum('ISOLATED', 'CROSS', name='margintype'), nullable=True),
    sa.Column('trading_fee', sa.Float(), nullable=True),
    sa.Column('expected_profit', sa.Float(), nullable=True),
    sa.Column('liquidation_price', sa.Float(), nullable=True),
    sa.Column('funding_rate', sa.Float(), nullable=True),
    sa.Column('entry_fee', sa.Float(), nullable=True),
    sa.Column('exit_fee', sa.Float(), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_count', sa.Integer(), nullable=True),
    sa.Column('max_profit_reached', sa.Float(), nullable=True),
    sa.Column('max_loss_reached', sa.Float(), nullable=True),
    sa.Column('final_outcome', sa.Float(), nullable=True),
    sa.Column('accuracy_improvement', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('price_updates', sa.JSON(), nullable=True),
    sa.Column('validation_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_signals')
    # ### end Alembic commands ###
