name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./trading_backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: |
        pytest tests/ --cov=app --cov-report=xml

    - name: Run linting
      run: |
        ruff check .
        mypy .

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/crypto-trading-pwa

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './frontend/crypto-trading-pwa/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

  deploy:
    needs: [backend-test, frontend-test]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install deployment dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r trading_backend/requirements.txt

    - name: Deploy backend
      run: |
        cd trading_backend
        python -m pip install -e .
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Deploy frontend
      run: |
        cd frontend/crypto-trading-pwa
        npm ci
        npm run build
        # Add deployment commands here
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
