name: CI/CD Pipeline

on:
  push:
    branches: [ "devin/*" ]
  pull_request:
    branches: [ "devin/1734564919-enhanced-sentiment-analysis" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: crypto_trading_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Enable Corepack
      run: |
        sudo corepack enable
        corepack prepare pnpm@latest --activate
        pnpm --version

    - name: Install Python dependencies
      working-directory: ./trading_backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install pytest pytest-asyncio pytest-cov pytest-env alembic psycopg2-binary

    - name: Verify Database Connection
      run: |
        python -c "
        import psycopg2
        import time
        for i in range(5):
            try:
                conn = psycopg2.connect('postgresql://postgres:postgres@localhost:5432/crypto_trading_test')
                conn.close()
                print('Database connection successful')
                exit(0)
            except psycopg2.OperationalError as e:
                print(f'Attempt {i+1}: {str(e)}')
                if i == 4:
                    print('Failed to connect to database after 5 attempts')
                    exit(1)
                time.sleep(2)
        "

    - name: Setup Database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d crypto_trading_test -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
      env:
        PGPASSWORD: postgres

    - name: Install Frontend dependencies
      working-directory: ./frontend/crypto-trading-pwa
      run: |
        pnpm install
        pnpm install -D vitest jsdom @testing-library/react @testing-library/jest-dom

    - name: Run Backend Tests
      working-directory: ./trading_backend
      env:
        PYTHONPATH: ${{ github.workspace }}/trading_backend
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/crypto_trading_test
        TESTING: "true"
      run: |
        python -c "
        import alembic.config
        import sys
        try:
            alembicArgs = [
                '--raiseerr',
                'upgrade', 'head',
            ]
            alembic.config.main(argv=alembicArgs)
            print('Database migrations completed successfully')
        except Exception as e:
            print(f'Migration failed: {str(e)}', file=sys.stderr)
            sys.exit(1)
        "
        pytest tests/ --cov=app --cov-report=xml

    - name: Run Frontend Tests
      working-directory: ./frontend/crypto-trading-pwa
      run: |
        pnpm test

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./trading_backend/coverage.xml
        fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies and linting tools
      working-directory: ./trading_backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install ruff black mypy types-all

    - name: Run Black
      working-directory: ./trading_backend
      run: black . --check

    - name: Run Ruff
      working-directory: ./trading_backend
      run: ruff check .

    - name: Run MyPy
      working-directory: ./trading_backend
      run: mypy app tests

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Enable Corepack
      run: |
        sudo corepack enable
        corepack prepare pnpm@latest --activate
        pnpm --version

    - name: Build Backend
      working-directory: ./trading_backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build
        python -m build

    - name: Build Frontend
      working-directory: ./frontend/crypto-trading-pwa
      run: |
        pnpm install
        pnpm build
